### ISSUE TITLE
KenLM versions?

### ISSUE THREAD

**Issue by fquirin** [synesthesiam/prebuilt-apps#1]
Hi @synesthesiam ,

I'm using the KenLM binaries and noticed a strange bug. In Arm64 everything runs smooth but in Arm32 the `--limit_vocab_file` leads to an empty ARPA file :fearful: 
I've tried both the `kenlm-20200308_armv7.tar.gz` and `kenlm-20210107_armv7.tar.gz`.

Do you remember if there was any difference in the build? (version etc.)

There is an open issue in the KenLM repo (https://github.com/kpu/kenlm/issues/177) suggesting that this is an unsolved problem in general but in the Arm64 version its working (haven't tested x86 again but I remember it was working too, ... I guess).

**Comment by synesthesiam** [comment]
They were compiled with the exact same commands, specifically:

```sh
cd /kenlm && \
    mkdir -p build && \
    cd build && \
    cmake -DFORCE_STATIC=on .. && \
    make -j 4
```

My first guess would be that there's a 64-bit assumption buried in the code somewhere. Looking through the code, I don't see anything obvious -- his C++ appears very clean and careful. If it's an algorithmic bug, then we're out of luck since I'm certainly not at his level!

**Comment by fquirin** [comment]
Ok, thanks for the info :+1: . It's a weird bug, maybe Kenneth can make sense of it at some point.
I've decided to drop `--limit_vocab_file` for the time being and to use a custom vocab check before the LM creation to show the user what words are missing. It seems to be a better solution anyway than letting words disappear without comment :sweat_smile: .
